### PR TITLE
Add webpack build configuration.

### PR DESCRIPTION
**Pull request by GeorgeSG**
## Summary
This PR adds a webpack build configuration and the build output files at the current version. This enables different ways to transpile and import the library.

## Configuration changes
Added `webpack.config.js`:
- The webpack build's configured entry is `/src/index.js` - it loads and transpiles all source via `babel-loader`. The output is stored in the `/lib/dist` folder.
- There are production and development modes. A mode can be selected with the `--mode` parameter of `webpack-cli`. The production mode adds `UglifyJs` as a build plugin and appends `.min` to the output file name.
- The `libraryTarget` is set to `var`, which is the default. For more options see the [webpack documentation](https://webpack.js.org/configuration/output/#output-librarytarget).

## New dependencies
The following development dependencies were introduced:
- `babel-loader` - to load and transpile the codebase.
- ~~`babel-preset-env` - a babel preset that determines the Babel plugins and polyfills needed for transpiling~~
- `uglifyjs-webpack-plugin` - uglifyjs for webpack
- `webpack`
- `webpack-cli`

No runtime dependencies introduced.

### CODE REVIEW

**Comment by jpellizzari** [comment]
Thanks for the contribution, @GeorgeSG. Can you explain which use case you are trying to address with this PR? We already transpile the library before uploading to NPM.

**Comment by GeorgeSG** [comment]
@jpellizzari the use case is using the library in an environment without module support (without AMD, CommonJS or something similar).

Basically, if you want to do `<script src="./prom.js"></script>`

**Comment by jpellizzari** [comment]
@GeorgeSG There needs to be a job that runs as part of the release process to generate the file to keep it up to date with the latest code changes. I think it would be best to distribute the compiled version via the NPM module.

I would also prefer to keep the compiled code out of version control.

**Comment by GeorgeSG** [comment]
@jpellizzari, I've integrated the webpack build in the publish process, and removed the original `dist` folder.

When calling `yarn build`, webpack will build in production mode in `lib/dist` and the file gets picked up when publishing.

**Comment by jpellizzari** [comment]
Excellent. Thanks for the contribution @GeorgeSG!

**Pull request merged**
